### ISSUE TITLE
4.18.0 fails to install on alpine

### ISSUE THREAD

**Issue by shadycuz** [python-jsonschema/jsonschema#1115] opened 2023-07-06 12:55 UTC
The latest release seems to have added or upgraded the `rpds-py` dependency. Our CICD builds started failing with this error: 

```
Collecting rpds-py>=0.7.1 (from jsonschema<5,>=3.0->cfn-lint==0.77.2)
  Downloading rpds_py-0.8.4.tar.gz (15 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Checking for Rust toolchain....
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ```
  
  I'm not sure when the need for rust was introduced but it is discussed here https://github.com/crate-py/rpds/issues/6
  
The fix to make builds pass again was to pin the previous `jsonschema` release:

```
- apk update && apk add git
- pip install --upgrade pip
- pip install jsonschema==4.17.3
- pip install pre-commit cfn-lint==0.77.2
```

This is also being tracked in https://github.com/aws-cloudformation/cfn-lint/issues/2790

**Comment by Julian** [comment] 2023-07-06 12:58
Duplicate of #1114.

**Closed by Julian** 2023-07-06 12:58 UTC

**Comment by oc-ben-ellis** [comment] 2023-07-06 13:00
@Julian Might be worth leaving one of these open to stop people raising duplicates and also to track the progress?

**Comment by shadycuz** [comment] 2023-07-06 13:01
@Julian ...

@oc-ben-ellis I was literally typing the same thing.

**Comment by Julian** [comment] 2023-07-06 13:04
I don't think leaving one open makes much difference on whether someone is going to file duplicates honestly.

There's nothing to do in this repository, if folks want to help feel free to find whatever knob needs tweaking upstream but things in this repository specifically are working as intended.

**Comment by shadycuz** [comment] 2023-07-06 13:11
I could be wrong, but I am expecting many GitHub issues to be created today as a result of the [release](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0 ).

Keeping open #1114 and pinning it, serves as a lighthouse to guide people to the upstream issue. While some will still create duplicates, some wont. I think this was created as a duplicate because #1114 had not be created when I started typing this one.
