### ISSUE TITLE
multipleOf validate bug

### ISSUE THREAD

**Issue by nazarov-ae** [python-jsonschema/jsonschema#930] opened 2022-04-05 17:28 UTC
hi

```bash
pip list | grep jsonschema
jsonschema          4.4.0
```

```python
import jsonschema
jsonschema.validate(instance=300.51, schema={'multipleOf': 0.01, 'type': 'number'})
jsonschema.validate(instance=300.52, schema={'multipleOf': 0.01, 'type': 'number'})
Traceback (most recent call last):
  File "/home/spice/.pyenv/versions/3.8.3/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/spice/dev/pik/amqp-handler/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 1022, in validate
    raise error
jsonschema.exceptions.ValidationError: 300.52 is not a multiple of 0.01
Failed validating 'multipleOf' in schema:
    {'multipleOf': 0.01, 'type': 'number'}
On instance:
    300.52

```

**Comment by Julian** [comment] 2022-04-05 17:32
Hi there. This is a dupe of #810 and others listed there.

**Closed by Julian** 2022-04-05 17:32 UTC
