### ISSUE TITLE
Draft 7 schema with an $id containing an empty fragment produces resolution errors for subresources

### ISSUE THREAD

**Issue by philvarner** [python-jsonschema/jsonschema#1064] opened 2023-03-21 17:03 UTC
This is an issue with 4.18.0a1 and 4.18.0a2, but not an issue with 3.x and 4.17 (and presumably all pre 4.18 versions). 

The following json file validates against the schema `https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json` prior to 4.18.0a1:

[S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json.txt](https://github.com/python-jsonschema/jsonschema/files/11031409/S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json.txt)

I'm using jsonschema thorough the stac-validator package, so this is what the outputs are from.

Running:

```
$ stac-validator out/S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json.txt

```

With jsonschema=4.17:

```
Thanks for using STAC version 1.0.0!

[
    {
        "version": "1.0.0",
        "path": "out/S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json",
        "schema": [
            "https://stac-extensions.github.io/sar/v1.0.0/schema.json",
            "https://stac-extensions.github.io/sat/v1.0.0/schema.json",
            "https://stac-extensions.github.io/eo/v1.0.0/schema.json",
            "https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json"
        ],
        "valid_stac": true,
        "asset_type": "ITEM",
        "validation_method": "default"
    }
]
```

with 4.18.0a2:

```
Thanks for using STAC version 1.0.0!

[
    {
        "version": "1.0.0",
        "path": "out/S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json.txt",
        "schema": [
            "https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json"
        ],
        "valid_stac": false,
        "error_type": "Exception",
        "error_message": "#/definitions/core"
    }
]
```

~~Additionally, it looks like these alpha releases where published to PyPI without the correct pre-release flag, so they're resolving for the constraint `>=3.2.0` that stac-validator has. It would be preferred for this not to be the case.~~

**Comment by philvarner** [comment] 2023-03-21 17:10
I originally had something about pre-releases resolving, but this has either been fixed or I had the alpha versions in my local cache.

**Comment by Julian** [comment] 2023-03-21 17:11
Hi there, please minimize your example to some specific example that you believe is incorrect, as certainly on its own this isn't necessarily indicative of a bug (and yeah as you modified, there's no such thing as marking something as a pre-release, so presumably what happened has to do with your setup)

**Comment by philvarner** [comment] 2023-03-21 17:21
Ok, here's the output just using jsonschema. If there is an additional parameter I need to set, I would not expect changes like this across minor versions.

```
pip install 'jsonschema==4.17.3'
jsonschema item.json -i out/S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json.txt
# no output, schema passes
jsonschema item.json -i out/S1A_EW_GRDM_1SDH_20220101T230242_20220101T230351_041273_04E7D5_F22B.json.txt
/Users/philvarner/.pyenv/versions/3.9.16/bin/jsonschema:5: DeprecationWarning: The jsonschema CLI is deprecated and will be removed in a future version. Please use check-jsonschema instead, which can be installed from https://pypi.org/project/check-jsonschema/
  from jsonschema.cli import main
Traceback (most recent call last):
  File "/Users/philvarner/.pyenv/versions/3.9.16/bin/jsonschema", line 8, in <module>
    sys.exit(main())
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/cli.py", line 239, in main
    sys.exit(run(arguments=parse_args(args=args)))
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/cli.py", line 293, in run
    exit_code |= _validate_instance(
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/cli.py", line 229, in _validate_instance
    for error in validator.iter_errors(instance):
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/validators.py", line 330, in iter_errors
    for error in errors:
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/_validators.py", line 335, in allOf
    yield from validator.descend(instance, subschema, schema_path=index)
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/validators.py", line 375, in descend
    for error in errors:
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/_validators.py", line 284, in ref
    yield from validator._validate_reference(ref=ref, instance=instance)
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/jsonschema/validators.py", line 404, in _validate_reference
    resolved = self._resolver.lookup(ref)
  File "/Users/philvarner/.pyenv/versions/3.9.16/lib/python3.9/site-packages/referencing/_core.py", line 548, in lookup
    raise exceptions.Unresolvable(ref=ref) from None
referencing.exceptions.Unresolvable: #/definitions/core
```

**Comment by Julian** [comment] 2023-03-21 17:27
Thanks, but it's again quite a bit more helpful for you to *minimize* your example rather than pointing to a big instance and big schema.

> If there is an additional parameter I need to set, I would not expect changes like this across minor versions.

Hard to say without diagnosing, which is why the minimized example would help. https://stackoverflow.com/help/minimal-reproducible-example has some notes (and specifically giving the minimal possible schema+instance which produces your issue is the most helpful bit in this case).

Regardless though, that isn't a good assumption to make. If there's a bug in this library that means that it doesn't have correct behavior according to the specification, that is exactly the sort of thing that may get fixed in minor versions (or even patch releases), so there's some chance it's your schema which is invalid, worked before, and now doesn't because that behavior was fixed. I won't guess what's more likely though, we may as well just look at the minimal example and see.

**Comment by Julian** [comment] 2023-03-21 18:36
For reference, here's what an essentially minimized example looks like:

```python
from jsonschema import validate
instance = {}
schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json#",
  "allOf": [{"$ref": "#/definitions/core"}],
  "definitions": {"core": {}}
}
validate(instance=instance, schema=schema)
```

where essentially it looks like your issue has to do with your `$id` containing an empty fragment (so removing the `#` fixes the issue).

I'll have to re-read the draft 7 specification, if I recall correctly, having an empty fragment is technically allowed, though discouraged (and there's notes in successive drafts saying that future drafts will probably make this an error).

You probably should consider removing it, though after reviewing the specs if it turns out this is indeed strictly speaking allowed even if discouraged, I'm happy to make a fix.

**Comment by philvarner** [comment] 2023-03-23 14:41
It is allowed in Draft7, and (as you can see in your example), the draft itself uses it in `$id` (which apparently why the the item schema used it).

Now that we're aware of the issue, we'll likely remove the empty fragment in a future release, but we're stuck with it for now.

**Closed as completed** 2023-03-23 19:17 UTC
