### ISSUE TITLE
Unable to validate from a second thread on v4.18a1 because jsonschema-specifications' registry cannot move between threads

### ISSUE THREAD

**Issue by remigermain** [python-jsonschema/jsonschema#1059] opened 2023-03-16 15:18 UTC
Hi, i have issue with last version `v4.18.0a1`
```
    File "/usr/local/lib/python3.9/site-packages/connexion/apps/abstract.py", line 149, in add_api
      api = self.api_cls(specification,
    File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 81, in __init__
      self.specification = Specification.load(specification, arguments=arguments)
    File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 194, in load
      return cls.from_file(spec, arguments=arguments)
    File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 148, in from_file
      return cls.from_dict(spec)
    File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 186, in from_dict
      return OpenAPISpecification(spec)
    File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 74, in __init__
      self._validate_spec(raw_spec)
    File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 88, in _validate_spec
      OpenApiValidator = create_spec_validator(spec)
    File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 34, in create_spec_validator
      InstanceValidator = extend_validator(Draft4Validator, {'type': NullableTypeValidator})
    File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 528, in extend
      return create(
    File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 185, in create
      specification = referencing.jsonschema.specification_with(
    File "/usr/local/lib/python3.9/site-packages/referencing/jsonschema.py", line 572, in specification_with
      resource = _SPECIFICATIONS.get(dialect_id)
    File "/usr/local/lib/python3.9/_collections_abc.py", line 763, in get
      return self[key]
    File "/usr/local/lib/python3.9/site-packages/referencing/_core.py", line 241, in __getitem__
      return self._resources[uri]
  pyo3_runtime.PanicException: assertion failed: `(left == right)`
    left: `ThreadId(4)`,
   right: `ThreadId(1)`: rpds::HashTrieMapPy is unsendable, but sent to another thread!  
```

`python==3.9`
`connexion==2.14.2`
`flask==2.2.3`

**Comment by Julian** [comment] 2023-03-16 15:28
I think that error message is saying something (connexion?) is trying to share a validator across threads. That wasn't safe even before, it's just failing harder now. I can try to look into it from this end, but something seems amiss downstream I think. Certainly would also help to have some reproducing code!

**Comment by Julian** [comment] 2023-03-16 15:41
OK sorry reading the traceback more carefully it looks like maybe it's calling `extend`, not sharing one single validator, will have to have a closer look.

**Comment by scv119** [comment] 2023-03-17 02:36
we are hitting the similar issues with this stack:
```
2023-03-16 19:35:08,230	INFO worker.py:1557 -- Connected to Ray cluster.
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `ThreadId(2)`,
 right: `ThreadId(1)`: rpds::HashTrieSetPy is unsendable, but sent to another thread!', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.18.1/src/impl_/pyclass.rs:876:9
stack backtrace:
   0:        0x116fb0d86 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb2b3f9f8dc23cb9d
   1:        0x116fc4aaa - core::fmt::write::h603bc3f9f076a504
   2:        0x116faed5c - std::io::Write::write_fmt::haffd946fd0c71703
   3:        0x116fb0b6a - std::sys_common::backtrace::print::hf660b768f462926e
   4:        0x116fb1ed3 - std::panicking::default_hook::{{closure}}::hb5b3e9f2c6b6790b
   5:        0x116fb1c28 - std::panicking::default_hook::ha10903320e35543e
   6:        0x116fb2603 - std::panicking::rust_panic_with_hook::h52ed83dd7c5d1444
   7:        0x116fb23d4 - std::panicking::begin_panic_handler::{{closure}}::h5f4e10879935eaea
   8:        0x116fb1228 - std::sys_common::backtrace::__rust_end_short_backtrace::hadc7b677a554f9f9
   9:        0x116fb209d - _rust_begin_unwind
  10:        0x116fcf443 - core::panicking::panic_fmt::hc10ef4c7e7c3da2e
  11:        0x116fcf767 - core::panicking::assert_failed_inner::h08d6c5cc53c5c1f2
  12:        0x116fc971e - core::panicking::assert_failed::h0d2fa838cecf0337
  13:        0x116f83a7b - <pyo3::impl_::pyclass::ThreadCheckerImpl<T> as pyo3::impl_::pyclass::PyClassThreadChecker<T>>::ensure::h462fd74793312081
  14:        0x116f71cef - rpds::_::<impl rpds::HashTrieSetPy>::__pymethod_insert__::h4d6474dd7abbe733
  15:        0x116f6b764 - pyo3::impl_::trampoline::trampoline_inner::hcfa2b419ff707fe2
  16:        0x116f70cd8 - rpds::_::<impl pyo3::impl_::pyclass::PyMethods<rpds::HashTrieSetPy> for pyo3::impl_::pyclass::PyClassImplCollector<rpds::HashTrieSetPy>>::py_methods::ITEMS::trampoline::hc13059f960f0beda
  17:        0x10ed089d0 - _method_vectorcall_VARARGS_KEYWORDS
  18:        0x10ee0be7a - __PyEval_EvalFrameDefault
  19:        0x10ecf91a4 - __PyFunction_Vectorcall
  20:        0x10ee0be7a - __PyEval_EvalFrameDefault
  21:        0x10ecf91a4 - __PyFunction_Vectorcall
  22:        0x10ee0be7a - __PyEval_EvalFrameDefault
  23:        0x10ecf94ec - __PyFunction_Vectorcall
  24:        0x10ecfe6fe - _method_vectorcall
  25:        0x10ee0bc11 - __PyEval_EvalFrameDefault
  26:        0x10ecf94ec - __PyFunction_Vectorcall
  27:        0x10ee0be7a - __PyEval_EvalFrameDefault
  28:        0x10ecf94ec - __PyFunction_Vectorcall
  29:        0x10ed7f9a4 - _slot_tp_init
  30:        0x10ed84e70 - _type_call
  31:        0x10ee0df4a - __PyEval_EvalFrameDefault
  32:        0x10ecf94ec - __PyFunction_Vectorcall
  33:        0x10ecfe6fe - _method_vectorcall
  34:        0x10ee0d712 - __PyEval_EvalFrameDefault
  35:        0x10ecf94ec - __PyFunction_Vectorcall
  36:        0x10ee0bc11 - __PyEval_EvalFrameDefault
  37:        0x10ecf91a4 - __PyFunction_Vectorcall
  38:        0x10ecfe6fe - _method_vectorcall
  39:        0x10ee0d712 - __PyEval_EvalFrameDefault
  40:        0x10ecf94ec - __PyFunction_Vectorcall
  41:        0x10ed83c5b - _vectorcall_method
  42:        0x10ed82cad - _slot_mp_ass_subscript
  43:        0x110f474e2 - _do_setitems
  44:        0x110f42f54 - _load
  45:        0x110f5261b - __pickle_loads
  46:        0x10ed54d61 - _cfunction_vectorcall_FASTCALL_KEYWORDS
  47:        0x10ee0d712 - __PyEval_EvalFrameDefault
  48:        0x10ecf91a4 - __PyFunction_Vectorcall
  49:        0x10ee0bc8b - __PyEval_EvalFrameDefault
  50:        0x10ecf94ec - __PyFunction_Vectorcall
  51:        0x10ee0be7a - __PyEval_EvalFrameDefault
  52:        0x10ecf94ec - __PyFunction_Vectorcall
  53:        0x10ee0be7a - __PyEval_EvalFrameDefault
  54:        0x10ed1153d - _gen_iternext
  55:        0x10edfea17 - _builtin_next
  56:        0x10ed54df7 - _cfunction_vectorcall_FASTCALL
  57:        0x10ee0bc8b - __PyEval_EvalFrameDefault
  58:        0x10ecf91a4 - __PyFunction_Vectorcall
  59:        0x10ee0bc8b - __PyEval_EvalFrameDefault
  60:        0x10ecf91a4 - __PyFunction_Vectorcall
  61:        0x10ee0bc8b - __PyEval_EvalFrameDefault
  62:        0x10ecf94ec - __PyFunction_Vectorcall
  63:        0x10ee0d179 - __PyEval_EvalFrameDefault
  64:        0x10ecf91a4 - __PyFunction_Vectorcall
  65:        0x10ee0be7a - __PyEval_EvalFrameDefault
  66:        0x10ecf91a4 - __PyFunction_Vectorcall
  67:        0x10ee0d179 - __PyEval_EvalFrameDefault
  68:        0x10ecf91a4 - __PyFunction_Vectorcall
  69:        0x10ee0be7a - __PyEval_EvalFrameDefault
  70:        0x10ecf91a4 - __PyFunction_Vectorcall
  71:        0x10ee0be7a - __PyEval_EvalFrameDefault
  72:        0x10ecf91a4 - __PyFunction_Vectorcall
  73:        0x10ecfe83f - _method_vectorcall
  74:        0x10eee69fa - _t_bootstrap
  75:        0x10ee86984 - _pythread_wrapper
  76:     0x7fff2070e8fc - __pthread_start
```

**Comment by Christian-B** [comment] 2023-03-17 11:12
We are facing similar issues.
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`

  left: `ThreadId(2)`,

 right: `ThreadId(1)`: rpds::HashTrieSetPy is unsendable, but sent to another thread!', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.18.1/src/impl_/pyclass.rs:876:9

This happens less than 1% of the time we run  jsonschema.validate 

We are using python3.8 with ALL our dependencies updated to the very latest pypi version at the start of each test run.

**Comment by dkfellows** [comment] 2023-03-17 11:22
> That wasn't safe even before, it's just failing harder now. 

The thread safety (or actual total lack thereof) of jsonschema is undocumented. The default assumption in Python then tends to be that an object can be used from a thread as long as it is the only thread manipulating the object (and appropriate synchronisation is used). That this is not true here violates the Principle of Least Surprise.

If you have critical thread-bound pieces in a multithreaded language like Python, _you need to document this very clearly._ Also, changing the behaviour to be less permissive in a point release is very user hostile.

**Comment by dkfellows** [comment] 2023-03-17 11:49
Well that's interesting. It looks like whatever is passing objects between threads is internal to jsonschema. The entirety of the file (less doc strings/comments) on our side that calls the code that fails is this (a thin wrapper to find schemas in the same directory):
```python
import os
import json
import jsonschema

def validate(json_obj, schema_filename):
    schema_file = os.path.join(os.path.dirname(__file__), schema_filename)
    with open(schema_file, "r", encoding="utf-8") as f:
        jsonschema.validate(json_obj, json.load(f))
```
It's used from multiple threads because we're running unit tests in parallel, but the only thing it passes between threads itself is the package reference. Whatever sabotage is going on is *definitely* a jsonschema bug as the schema itself is being loaded from a file in the current thread and never passed to another.

**Comment by dkfellows** [comment] 2023-03-17 12:13
Looks like commit eb004479645a4e1f0d842e4434b909f476569dcc broke this by effectively thread-binding the internal caching/resolution mechanism inside jsonschema. That's not user-exposed, so it is not reasonable to expect users to understand how to work around this.

**Comment by Julian** [comment] 2023-03-17 12:20
> Whatever sabotage is going on is definitely a jsonschema bug

Check your tone please, it isn't appropriate, especially for an issue ticket about an alpha release.

There is no "sabotage", and as I said, I can have a look at this to see if this is easily fixable in the next few days. Feel free to share diagnosis, PRs, or code. Commentary though on what you think python's norms are or guilt trips or the like you can keep to yourself.

Thanks to all of you who've tried out the alpha it's of course super helpful and appreciated.

**Comment by dkfellows** [comment] 2023-03-17 12:45
I apologise for the "sabotage" word, but sometimes it feels a bit like it when an unannounced upstream change breaks things deep in one's own tests.

The test case is to validate using the main `jsonschema.validate` function from two threads, albeit sequentially (so there is no question of actual concurrent modification; I can understand not being happy to support that). The workload for the threads should load a schema from a file and validate it against JSON generated in that thread. I've already posted the code we're using, but it's the most trivial thing ever (and the schemas themselves are mostly pretty simple too).

I've not yet identified whether having any `$ref` nodes in the schema is required to trigger the problem, but I suspect not (they're only used in one of our schemas and that's not one we normally validate with).  Things are chopped around a bit by our CI system because it doesn't expect this sort of issue to crop up, so I can't actually identify properly which schema was participating.

**Comment by Julian** [comment] 2023-03-17 12:58
?? You should have stopped at "I apologise", I don't know what you mean by it feels like sabotage when we're again talking about an alpha release which you are opting into to help test the next version out and iron out bugs. That *is* the announcement, the alpha.

**Comment by p1c2u** [comment] 2023-03-20 06:00
The problem is in Registry that uses `HashTrieMapPy` to store `_resources`which is a rust wrapper pyclass define as unsendable ( no `Send` implemented) so you can't share the registry object between threads. The workaround can be 
pyrsistent implementation of Registry.

**Comment by Julian** [comment] 2023-03-20 17:03
I believe this should now be fixed (either by reinstalling, which will pull in a new version of a dependency, or by installing `v4.18.0a2` which should be released in a few minutes and which will bump the minimum version of the dependency).

Those who are installing the pre-release please let me know if that isn't the case! (Or of course again if you have other comments or issues feel free to open them.)

**Comment by Julian** [comment] 2023-03-20 17:06
> Currently the workaround can be pyrsistent implementation of Registry.

pyrsistent was removed and replaced by rpds precisely because it's unfortunately quite slow on CPython. I may at some point get some time to help look at why, but I wrote rpds.py (bindings to rpds) for the exact reason that it's around *4x* faster in some microbenchmarks.

(Of course all the above unfortunately applies to CPython -- on PyPy things are way way faster than CPython and indeed even faster using pyrsistent's pure Python implementation than the Rust one, so at some point the pyrsistent implementation will indeed come back, but that will be specifically for PyPy.)

**Closed** 2023-03-21 14:00 UTC
Labels: Bug
