### ISSUE TITLE
urlopen error using RefResolver in v4.18

### ISSUE THREAD

**Issue by captaincoordinates** [python-jsonschema/jsonschema#1119] opened 2023-07-07 17:09 UTC
According to [the release notes](https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v4180) 4.18.0 _should_ be backwards compatible, but it is not.

I'm calling `jsonschema.validate` like this:
```python
from json import load
from jsonschema import RefResolver, validate

with open("/schema/src/validation/core-meta-schema.json", "r") as f:
    schema = load(f)
with open("/schema/versions/v1/name.schema.json", "r") as f:
    document = load(f)
validate(
    document,
    schema,
    resolver=RefResolver(
        base_uri=f"file:///schema/src/validation/core-meta-schema.json",
        referrer=schema,
    ),
)
```

This code executes fine in 4.17.3 but fails in 4.18.0 with
```
<urlopen error [Errno 2] No such file or directory: '/schema/src/validation/meta/core'>
```
It looks like the value passed to `base_uri` is no longer allowed to contain hyphens.

**Comment by Julian** [comment] 2023-07-07 17:53
Please provide a fully working example to reproduce.

**Comment by captaincoordinates** [comment] 2023-07-11 04:39
Fully working example available [here](https://github.com/captaincoordinates/jsonschema-4.18-bug)

**Comment by roll** [comment] 2023-07-11 08:49
Hi I can confirm regression with `4.18` with errors like `jsonschema.exceptions._WrappedReferencingError: Unresolvable: https://frictionlessdata.io/schemas/data-package.json`

**Comment by Julian** [comment] 2023-07-12 12:12
Do you have an example that does not involve validating using the draft2020-12 metaschema (which by the way your example is trying to validate a draft 7 schema using the draft 2020-12 metaschema, which I assume is not what you mean to do)?

But one of the reasons that the `referencing` library was written was precisely to make `$dynamicRef` possible to implement sanely -- in `4.17.x` and previous versions, it essentially did not work (i.e. did not validate what you asked it to validate correctly). It's certainly possible that some examples that previously passed silently now raise exceptions, but I'm not sure how much effort I'd be willing to put in to fix that, as they were broken before too just silently broken -- if you have examples that don't involve `$dynamicRef` and/or don't involve the metaschema those are a lot more useful to look at.

**Comment by captaincoordinates** [comment] 2023-07-12 16:34
No, sorry, I don't have another example. This is the use-case that failed for me so this is the one I'm reporting.

As for using the metaschema - and the specific version of it used here - the code attempts to validate a document against a schema. I don't understand why the specific content of the schema would be a significant factor here?

I'm not familiar with the problem you describe around dynamic refs and how it's addressed by the `referencing` library, but would just note that the [pypi](https://pypi.org/project/jsonschema/) page for this project describes

> Full support for [Draft 2020-12](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft202012Validator), [Draft 2019-09](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft201909Validator), [Draft 7](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft7Validator), [Draft 6](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft6Validator), [Draft 4](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft4Validator) and [Draft 3](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft3Validator)

is that not the case?

I'm grateful for having the `jsonschema` package in the pypi ecosystem, and to you for maintaining a popular package, but I may need to look at other tools if `refs` are not well supported.

**Comment by Julian** [comment] 2023-07-12 16:43
You are noting language which appears in 4.18, where indeed full support is present and ref works well. As I mentioned, that's not the case in 4.17, where the language you quoted does not appear.

**Comment by captaincoordinates** [comment] 2023-07-13 20:45
Thanks, that's good to know, but surely this means there shouldn't be any problem with my example including refs?

**Comment by Julian** [comment] 2023-07-18 08:24
Your example is using the 4.17 APIs - -the 4.18 APIs use the `referencing` library which was written as mentioned precisely to provide a fully functioning, compliant, correct implementation of reference resolution.

**Comment by Julian** [comment] 2023-07-18 08:27
I'm going to close this as essentially being related to something that didn't work previously in 4.17 either (and simply was passing silently), but if you or anyone else ends up having an example which differs in behavior and does not rely on `$dynamicRef` validation, or otherwise have questions, please do feel free to follow up.

**Closed by Julian** 2023-07-18 08:27 UTC
Labels: Needs Simplification
