### ISSUE TITLE
referencing is less lenient with $refs

### ISSUE THREAD

**Issue by ikonst** [python-jsonschema/jsonschema#1070] opened 2023-03-24 19:51 UTC
```python
import jsonschema

jsonschema.validate(
    instance={
        'foo': 'not-a-number'
    },
    schema={
        'type': 'object',
        '$ref': '#$defs/foo',  # <-- culprit, should be "#$/defs/foo"
        '$defs': {
            'foo': {
                'type': 'number',
            },
        },
    },
)
```

In 4.17:
```
jsonschema.exceptions.ValidationError: {'foo': 'not-a-number'} is not of type 'number'
```

In 4.18.0a2
```
referencing.exceptions.NoSuchAnchor: '$defs/foo' does not exist within {'type': 'object', '$ref': '#$defs/foo', '$defs': {'foo': {'type': 'number'}}}
```

Similar things that worked before and fail now are:
- `foo.json#/`
- `foo.json#$defs/foo`

What could make it better IMO:
- add a mention in docs/referencing.rst if becoming stricter is desired
- is it a `referencing` issue? (not sure if it _should_ be more lenient)
- have jsonschema help the user, i.e. "<a> used to work but no longer does, did you mean <b>?"

WDYT?

**Comment by Julian** [comment] 2023-03-24 20:18
Those are invalid JSON pointers (so they indeed shouldn't work). The slash is required. It'd be an accident if they worked before, the spec is always the "guiding principle of what should be expected to work", though of course I can't expect everyone to know it by heart, but it's what decides whether something is a bug fix or not essentially. I'm definitely OK with some of the suggestions there -- specifically:

* a PR in referencing that tries to guess whether you meant a JSON Pointer and suggests better language (since the interpretation if you miss the `/` is that you mean a plain name fragment and not a JSON Pointer, but slashes are not valid for plain name fragments so if we see one it's likely someone meant a JSON Pointer and screwed up the syntax.)
* a mention in the `jsonschema` referencing docs that the behavior more closely reflects the spec, though saying so was precisely my intention by saying "referencing will begin in beta, but already is more compliant than the existing $ref support. This change is a culmination of a meaningful chunk of work to make $ref resolution more flexible and more correct." in the CHANGELOG. If you have a place you think you'd have been more likely to look, or that future people will, of course happy to add that somewhere else, or hear other suggestions!

**Comment by Julian** [comment] 2023-03-26 17:48
I got a minute to implement the first of those two bullets somewhat easily (in the linked commit, which is part of referencing v0.26).

PRs are certainly helpful for any additional things you suspect would help others, otherwise going to close this as it's essentially working as intended. Thanks.

**Closed by Julian** 2023-03-26 17:48 UTC

**Comment by ikonst** [comment] 2023-03-27 01:31
@Julian I left some comments on the commit.

Also, this doesn't address `foo.json#/` which also became invalid. (I'm getting those "test cases" out of a corpus of JSONSchemas we have here at Lyft.)

**Comment by Julian** [comment] 2023-03-27 12:31
> foo.json#/

`#/` is not invalid, it represents a pointer to an empty string, i.e. to `{"foo": "bar"}` in `{"": {"foo": "bar"}}`.

**Comment by ikonst** [comment] 2023-03-27 13:16
Could it be that the previous implementation treated it as a pointer to the root? If so, it could be a nice touch for `PointerToNowhere` to provide a suggestion.

**Comment by Julian** [comment] 2023-03-27 15:32
v0.26.2 adds a suggestion for `PointerToNowhere` as well.
