### ISSUE TITLE
Cargo, the Rust package manager, is not installed or is not on PATH.

### ISSUE THREAD

**Issue by paxapy** [python-jsonschema/jsonschema#1116] opened 2023-07-06 13:29 UTC
Seems like with latest minor update we got Rust dependency which looks odd for python package.
My CI test traceback:

```
Downloading jsonschema_specifications-2023.6.1-py3-none-any.whl (17 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6.0->drf-spectacular==0.25.1->-r requirements/base.txt (line 48))
  Downloading referencing-0.29.1-py3-none-any.whl (25 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=2.6.0->drf-spectacular==0.25.1->-r requirements/base.txt (line 48))
  Downloading rpds_py-0.8.4.tar.gz (15 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
```

I think it's worth to at least mention Rust dependency in a changelog or avoid this change in minor release.

**Comment by shadycuz** [comment] 2023-07-06 13:34
Unfortunately, this is a duplicate of #1114 and #1115 

A workaround is documented in https://github.com/aws-cloudformation/cfn-lint/issues/2790, that might work for you.

**Closed** 2023-07-06 13:46 UTC
