### ISSUE TITLE
Installing ddtrace breaks tests with the jsonschema library

### ISSUE THREAD

**Issue by fr-ser** [python-jsonschema/jsonschema#1289] opened 2024-07-26 06:29 UTC
Strictly speaking it might be more a bug with ddtrace (and I opened a ticket here: <https://github.com/DataDog/dd-trace-py/issues/9950>).

But maybe the jsonschema experts also know fix?

### Summary of problem

Just installing (not even using) the newest version of ddtrace causes the tests to break, when the `jsonschema` package is used.

### Which version of jsonschema are you using?

4.23.0

### Which version of pip are you using?

pip 23.3.2 (python 3.8)

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
attrs==23.2.0
exceptiongroup==1.2.2
importlib_resources==6.4.0
iniconfig==2.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
packaging==24.1
pkgutil_resolve_name==1.3.10
pluggy==1.5.0
pytest==8.3.2
referencing==0.35.1
rpds-py==0.19.1
tomli==2.0.1
zipp==3.19.2
</details>

### How can we reproduce your problem?

Here is a repository with a reproducible example: <https://github.com/fr-ser/bug-example-ddtrace-jsonschema>

Here is a summary of that repo:

1. Install the environment: `poetry install --no-root`
2. Run the test: `poetry run pytest`
3. See an error
4. uninstall ddtrace: `poetry remove ddtrace`
5. run the test: `poetry run pytest`
6. it works ¯\_(ツ)_/¯

### What is the result that you get?

```txt
    test_main.py:1: in <module>
        import jsonschema
    <frozen importlib._bootstrap>:991: in _find_and_load
        ???
    <frozen importlib._bootstrap>:975: in _find_and_load_unlocked
        ???
    <frozen importlib._bootstrap>:671: in _load_unlocked
        ???
    .venv/lib/python3.8/site-packages/ddtrace/internal/module.py:220: in _exec_module
        self.loader.exec_module(module)
    .venv/lib/python3.8/site-packages/jsonschema/__init__.py:16: in <module>
        from jsonschema.validators import (
    <frozen importlib._bootstrap>:991: in _find_and_load
        ???
    <frozen importlib._bootstrap>:975: in _find_and_load_unlocked
        ???
    <frozen importlib._bootstrap>:671: in _load_unlocked
        ???
    .venv/lib/python3.8/site-packages/ddtrace/internal/module.py:220: in _exec_module
        self.loader.exec_module(module)
    .venv/lib/python3.8/site-packages/jsonschema/validators.py:603: in <module>
        meta_schema=SPECIFICATIONS.contents(
    .venv/lib/python3.8/site-packages/referencing/_core.py:483: in contents
        return self[uri].contents
    .venv/lib/python3.8/site-packages/referencing/_core.py:333: in __getitem__
        raise exceptions.NoSuchResource(ref=uri) from None
    E   referencing.exceptions.NoSuchResource: 'http://json-schema.org/draft-03/schema#'
    ========================================================================================================== short test summary info ===========================================================================================================
    ERROR test_main.py - referencing.exceptions.NoSuchResource: 'http://json-schema.org/draft-03/schema#'
 ```

### What is the result that you expected?

No error

**Comment by Julian** [comment] 2024-08-22 15:50
Realistically, whatever this is is going to be almost certainly a bug in dd-trace -- specifically it's not even "normal" clearly that ddtrace appears in an import traceback of some other library (so obviously it's instrumenting the import process and doing so in a way that's interfering with importlib.resources). I'd love to say I can dedicate time to diagnosing what/why that is, but realistically I doubt I'll have the time unfortunately, and this should be reproducible without involving `jsonschema` at all presumably.

I'm going to close this as "nearly certainly not a bug here", but as I say I can happily perhaps consult on the dd-trace bug if someone else does a bit of digging.

@catid-saronic please open a new bug with a reproducer, as yours will somewhat clearly be different given the presence of dd-trace in the traceback there.

**Closed by Julian** 2024-08-22 15:50 UTC

**Comment by Julian** [comment] 2024-08-22 15:53
@fr-ser just seeing now that in the beginning of your report you also mention that this is likely a ddtrace bug -- I think a good first step for your reproducer is perhaps to remove the need to use poetry, just to eliminate the possibility that it's poetry's bug (so make it so the repo is installable with pip and/or uv as well, which right now just trying blows up here if I try to install it with pip).

**Comment by catid-saronic** [comment] 2024-08-22 16:03
I was able to fix the bug in my setup by removing an old version of jsonschema-specifications from the conda base env that was leaking into my conda env

**Comment by timmc-edx** [comment] 2024-08-22 16:03
It's not specific to poetry, as I'm seeing it just with `pip install`.

**Comment by Julian** [comment] 2024-08-22 16:08
@timmc-edx yeah I didn't expect it to be, just a good thing to eliminate considering I *think* poetry vendors a version of jsonschema, but it seems ~90% likely to me to be ddtrace + importlib.resources related.
