### ISSUE TITLE
jsonschema 4.10.0 has broken ASDF

### ISSUE THREAD

**Issue by WilliamJamieson** [python-jsonschema/jsonschema#981] opened 2022-08-16 17:17 UTC
The release today of `jsonschema 4.10.0` seems to have broken ASDF in quite badly, see asdf-format/asdf#1172. Everything appears to function correctly with `jsonschema 4.9.1`, and none of the changes between the versions stand out to me as a likely cause of the issue.

There are at least two (possibly related errors) that I am seeing:

1. A brand new deprecation warning about a meta schema not being found originating here: https://github.com/python-jsonschema/jsonschema/blob/ae0feea5e5e8c1a80efb1f17a20b15295355518a/jsonschema/validators.py#L1103-L1111 ASDF makes extensive use of a metaschema and it seems that `jsonschema` is no longer able to find the metaschema ASDF is using.
2. More seriously, we get the error:
```
AttributeError: 'list' object has no attribute 'get'
```
originating here: https://github.com/python-jsonschema/jsonschema/blob/ae0feea5e5e8c1a80efb1f17a20b15295355518a/jsonschema/validators.py#L92-L98 Which again indicates to me that something has gone wrong with how ASDF is communicating schema information with `jsonschema`.

I suspect there is a common cause of the issues ASDF is experiencing. I appreciate any help that can be offered.

**Comment by WilliamJamieson** [comment] 2022-08-16 17:43
Looking more deeply at the new warning issue I think the change that is breaking ASDF is the change from `[attr.evolve`](https://github.com/python-attrs/attrs/blob/9f745505190973f4e3ebc8464aee0d1eedbb11cb/src/attr/_funcs.py#L344-L370) to this slightly different `evolve` method: https://github.com/python-jsonschema/jsonschema/blob/ae0feea5e5e8c1a80efb1f17a20b15295355518a/jsonschema/validators.py#L204-L218

In particular, I suspect the issue is that by using the `validator_for`: https://github.com/python-jsonschema/jsonschema/blob/ae0feea5e5e8c1a80efb1f17a20b15295355518a/jsonschema/validators.py#L1079-L1112 method to get a new class instance, ASDF is getting a `Draft202012Validator` rather than a `Draft4Validator` (hence the warning). Currently, ASDF is only compatible with the Draft4 specification.

Are there any suggestions on how I can fix this issue?

**Comment by Julian** [comment] 2022-08-16 19:18
Hi. Please include some information about what reproduces the issue being reported. I'm not familiar with asdf, so ideally it should just be some Python code using this library, in which case I'd be happy to help diagnose.

**Comment by WilliamJamieson** [comment] 2022-08-16 19:44
> Hi. Please include some information about what reproduces the issue being reported. I'm not familiar with asdf, so ideally it should just be some Python code using this library, in which case I'd be happy to help diagnose.

To reproduce the error:
```python
import asdf

af = asdf.AsdfFile({'a': 3 + 2j})
af.write_to('test.asdf')
```

**Comment by Julian** [comment] 2022-08-17 09:03
Thanks -- I was hoping you'd include code specifically for this library, which makes it easier than having to diagnose asdf itself, which as I mentioned I don't really have any familiarity with. You may also want to have a look at #982 -- are you perhaps subclassing validator classes for some reason?

**Comment by Julian** [comment] 2022-08-17 12:30
OK I got a minute to look, and indeed that seems to be the issue: https://github.com/asdf-format/asdf/blob/e0a6081e82bf69b9ce5f8dfa5b3dee5e85000e26/asdf/schema.py#L261

That's honestly not something that's really ever been supported, though of course without an error saying so it's unsurprising some folks did it :/ (here and #982).

I believe there should be a minor fix that will probably make it work again for you, but I do intend to put the warning in finally and eventually make it error to subclass these -- as I say it's not something I've ever really wanted to support and isn't something I check carefully when making changes. Whatever is being done there should be possible without subclassing, though I'm certainly happy to help figure out how if need be, feel free to ping me. Perhaps I'll close this and we can centralize in #982 if that's OK with you, as I say, I hope I can make what you have work regardless.

**Comment by robherring** [comment] 2022-08-17 18:06
I think I'm seeing similar issues as well. Even if I rework things to not subclass the validator, it seems evolve() looses my custom resolver. That's about as far as I've gotten debugging it.

**Comment by robherring** [comment] 2022-08-17 23:35
I think the issue is related to validator_for() not finding the right validator if $schema URI doesn't quite match. Either a trailing '#' or http vs. https or both causes a mismatch. For dtschema, we're on draft2019-09 and now draft2020-12 validator gets selected at some point. I guess now that the validator is selected for each schema file instead of being fixed by the caller, a mismatched URI causes problems.

**Comment by Julian** [comment] 2022-08-18 06:23
Do you have anything I can run to reproduce? The default for `validator_for` is to reuse the same validator class, so even with broken schemas the behavior should be the same, but clearly there's something happening.

**Comment by Julian** [comment] 2022-08-18 06:50
OK never mind I see the second issue -- which has to do with the subclasses also not using [jsonschema.validators.validates](https://python-jsonschema.readthedocs.io/en/stable/creating/#jsonschema.validators.validates) to decorate the class (which registers the `$schema` value). Without it `jsonschema` doesn't know that that URI is handled by your validator class. Normally this is handled automatically if you don't subclass, but if you do, you'd need to use it.

But, even without that, there was a second bug ("unrelated") which was `validator_for` not using a default validator when `$schema` was present in an instance -- in other words combined with the above, this meant that the latest version was being used because `jsonschema` didn't know what validator was responsible for your `$schema`.

I've fixed the latter, though yeah you should still stop inheriting from validators :)

**Closed** 2022-08-18 07:01 UTC

**Comment by Julian** [comment] 2022-08-19 08:22
Cool. The first step should I think be to decouple your class from `Validator` -- i.e. if you want a method called `iter_errors` just start with your own class that looks more like:

```python
@attr.s
class ASDFValidator:
    _validator = attr.ib()

    def iter_errors(self, *args, **kwargs):
        do_stuff()
        result = self._validator.iter_errors(*args, **kwargs)
        do_more_stuff()
        return asdfresult
```

but I'd have to look closer to give more specific advice. I may have some time next week, so if you get stuck do ping me (here or on your repo).
